version: '3.1'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - ./pg_data:/var/lib/postgresql/data
      - ./database_init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
